-- Real-Time Streaming Pipeline: Snowflake database, schema, and raw table
-- Run these commands in a Snowflake worksheet.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE REALTIME_STREAMING_DB;
CREATE OR REPLACE SCHEMA REALTIME_STREAMING_DB.RAW;

USE DATABASE REALTIME_STREAMING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE STREAMING_EVENTS_RAW (
    DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
