USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REALTIME_STREAMING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT JSON_FILE_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE S3_RAW_STAGE
  STORAGE_INTEGRATION = S3_REALTIME_INT
  URL = 's3://dea-realtime-streaming-data-jenny/raw/'
  FILE_FORMAT = JSON_FILE_FORMAT;

-- Verifies Snowflake can see the files in S3.
LIST @S3_RAW_STAGE;
