USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE REALTIME_STREAMING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE STREAMING_EVENTS_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO STREAMING_EVENTS_RAW (DATA)
FROM (
  SELECT $1
  FROM @S3_RAW_STAGE
)
FILE_FORMAT = JSON_FILE_FORMAT;

-- Copy the notification_channel value.
-- It is the SQS queue ARN used in the S3 event notification setup.
SHOW PIPES;
